language: java
script: mvn clean install

jdk:
    - oraclejdk8

notifications:
  webhooks:
    urls:
      - env.GITTER_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false